name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --name mongodb
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
    
    - name: Setup environment variables
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/test_db" >> .env
        echo "JWT_SECRET=test_secret_for_ci" >> .env
        echo "CLOUDINARY_CLOUD_NAME=dummy" >> .env
        echo "CLOUDINARY_API_KEY=dummy" >> .env
        echo "CLOUDINARY_API_SECRET=dummy" >> .env
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Start backend server
      run: |
        node app.js &
        sleep 5
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/test_db
        JWT_SECRET: test_secret_for_ci
    
    - name: Run Playwright tests
      run: npx playwright test
      env:
        NODE_ENV: test
        CI: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
